# Generated by Django 5.2.4 on 2025-07-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
