# Generated by Django 5.2.4 on 2025-07-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_rename_realease_date_website_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('N', 'Not Reviewed'), ('E', 'Error'), ('A', 'Accepted'), ('D', 'Denied')], max_length=1),
        ),
    ]
